### ISSUE TITLE
Access to repository not available after sponsorship

### ISSUE THREAD

**Issue by ilyafish** [ui-devtools/readme#1]
Forgive me if there's a better way to contact you - I am new to all of this and couldn't find a way to message directly. I'll delete this later. I sponsored you but am still unable to see the repository. Thanks!

**Comment by armenr** [comment]
+1 -- Same here!

**Comment by robertalanm** [comment]
+1 -- same here

**Comment by soultellegend** [comment]
+1 -- same here

**Comment by siddharthkp** [comment]
All of you should have access to the org now, sorry about my automation fail!
