### ISSUE TITLE
Hi, I have sponsored you as `deco-cx` org, how do I get access to the repos?

### ISSUE THREAD

**Issue by vibegui** [ui-devtools/readme#2]

**Comment by vibegui** [comment]
@siddharthkp help? 🙏

**Comment by siddharthkp** [comment]
Yes! Thanks for reaching out, the automation was failing because deco-cx is an org and I wasn't sure where to go from there :)

You should have an invitation in your inbox :)

**Comment by vibegui** [comment]
Sorry, @siddharthkp, I've lost track of this and the invite expired. Can you send it again? Cheers

**Comment by siddharthkp** [comment]
Done :)
