### ISSUE TITLE
Access to @ui-devtools/tailwind after sponsorship

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [ui-devtools/readme#3]
Hi @siddharthkp, can I have access to @ui-devtools/tailwind?

**Comment by siddharthkp** [comment]
Hi!

my bad, the automated job failed 🙃

Added you to the team now, you should have an invitation in your emails/notifications

**Comment by pawelkrystkiewicz** [comment]
@siddharthkp thanks :+1:
