### ISSUE TITLE
Access to @ui-devtools/tailwind after sponsorship

### ISSUE THREAD

**Issue by nagarajan010** [ui-devtools/readme#4]
Hi,
how do i get access to @ui-devtools/tailwind after sponsorship

Thanks

**Comment by siddharthkp** [comment]
(In case you didn't receive a notification for the invitation)

I already you to the team, you should have a notification or email for that. Or you can visit the team page: https://github.com/orgs/ui-devtools/teams/sponsors

Let me know if you don't see it, I can add you again :)
